config/routes.rb
Rails.application.routes.draw do
  root 'lab9#input'
  post '/view', to: 'lab9#view'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lab9_controller.rb
class Lab9Controller < ApplicationController
  def input
  end

  def view
    n_r = params[:n_s]
    if n_r != nil then
      if n_r.match?(/^\d+$/) then
        n_r = params[:n_s].chomp.to_i
        @res_x = []
        @k = 0
        (1..n_r).each { |x|
          if (x**2).to_s == (x**2).to_s.reverse
            @res_x.push(x)
            @k += 1
          end
        }
      else
        @res_x = 'Введите число правильно: только целое число без пробелов'
        @k = -1
      end
    else
      @res_x = 'Введите число правильно: только целое число без пробелов'
      @k = -1
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lab9_helper.rb
module Lab9Helper
end

app/views/lab9/_view_message.html.erb
<p id="result">Ваш результат: </p>
<% if @k == -1%>
<p> <%= @res_x%> </p>
<% else %>
<table>
  <tr>
    <td>Число</td><td>Квадрат числа</td>
  </tr>
  <% @res_x.each do |x| %>
    <tr>
      <td><%= x %></td>
      <td><%= x**2 %></td>
    </tr>
  <% end %>
</table>
<p>Всего чисел: <%= @k %> </p>
<% end %>

app/views/lab9/input.html.erb
<h1>Lab9#input</h1>
<p>Find me in app/views/lab9/input.html.erb</p>
<%= form_with url: view_path do |form| %>
 <%= form.label("Input n:") %>
 <%= form.text_field(:n_s) %> <br/>
 <br/><%= form.submit("Enter") %>
<% end %> 
<div id='view-container'></div>

app/views/lab9/view.turbo_stream.erb
<%= turbo_stream.update 'view-container', partial: 'view_message' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab9</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>